### ISSUE TITLE
User photos in "Recent Active Users" widget point to invalid image

### ISSUE THREAD

**Issue by linc** [vanilla/wordpress-vanilla#12]
Paraphrased [report from user](https://vanillaforums.org/discussion/32352/there-is-a-small-bug-in-the-vanilla-plugin-for-wordpress):

> Recent Active Users shows small user photos in the footer but the images are pointing to a non-existent jpg file. Specifically its missing the letter "n" from the jpg file name in the begining. So for example the plugin is trying to load the photo in /forum/uploads/userpics/801/N0L9X51Q00H2.jpg when the actuall photo is named nN0L9X51Q00H2.jpg. So its missing an "n" in the beggining in every photo.

The missing code is `Gdn_Upload::url(changeBasename($Value, 'n%s'));` which will need to get reproduced appropriately in the WordPress plugin.

Please note calls to usericon.png may be effected by a change here. It needs actual testing, not just a blind patch.

**Comment by DaazKu** [comment]
[The Wordpress plugin logic is "correct"](https://github.com/vanilla/wordpress-vanilla/blob/a57b7b16706ff42cb4591035f67eda11add3ea1f/functions.php#L418) and I don't know exactly how to change it in a reliable way.

The problem comes from this change: https://github.com/vanilla/vanilla/commit/4238105fec5e74cc7d0ed9c4047dcc50440d8e9e

Should we update the fix to point to the "p" version of the photo?

**Comment by linc** [comment]
It looks like the correct change would have been `$Row->Photo = Gdn_Upload::url(changeBasename($Row->Photo, 'p%s'));`. I'm not clear why I might have left off the p in this situation.

**Comment by DaazKu** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/4343
